# Generated by Django 3.0.1 on 2022-03-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220308_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasks',
            field=models.TextField(default=' ', max_length=100),
        ),
    ]
