# Generated by Django 3.0.1 on 2022-03-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(max_length=20)),
            ],
        ),
    ]
