# Generated by Django 4.0.2 on 2022-03-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_kymyz_delete_drinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kymyz',
            old_name='kymyz',
            new_name='shelpek',
        ),
    ]
