# Generated by Django 4.0.2 on 2022-03-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_kymyz_kymyz_shelpek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kymyz',
        ),
    ]
