# Generated by Django 4.0.2 on 2022-03-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_airan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='weight',
        ),
    ]
