# Generated by Django 4.0.2 on 2022-04-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_book_picture_alter_book_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Takyryp')),
                ('is_published', models.BooleanField(default=True, verbose_name='shygarylym')),
            ],
        ),
    ]
